import { Facility, Program, DayOfWeek } from './types';

// Helper functions for formatting
export function formatAgeRange(minMonths: number, maxMonths: number): string {
  const formatAge = (months: number): string => {
    if (months < 12) return `${months}mo`;
    const years = Math.floor(months / 12);
    const rem = months % 12;
    if (rem === 0) return `${years}yr`;
    return `${years}yr ${rem}mo`;
  };
  return `${formatAge(minMonths)} - ${formatAge(maxMonths)}`;
}

export function formatCost(amount: number | null, period: string, notes?: string): string {
  if (amount === null) return 'Contact for pricing';
  if (amount === 0) return 'Free';
  
  const formatted = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(amount);
  
  const periodMap: Record<string, string> = {
    'hourly': '/hr',
    'daily': '/day',
    'weekly': '/wk',
    'monthly': '/mo',
    'yearly': '/yr',
  };
  
  return `${formatted}${periodMap[period] || ''}`;
}

export function formatSchedule(program: Program): string {
  const { daysPerWeek, hoursPerDay } = program;
  return `${daysPerWeek}d/wk, ${hoursPerDay}hr/day`;
}

export function formatScheduleDetails(program: Program): string {
  const { daysPerWeek, daysOffered, hoursPerDay, startTime, endTime } = program;
  const days = daysOffered.join('/');
  return `${days} (${daysPerWeek}d/wk) • ${startTime} - ${endTime} (${hoursPerDay}hrs)`;
}

export function formatEnrollmentStatus(program: Program): string {
  if (program.enrollmentStatus === 'open') {
    if (program.enrollmentDeadline) {
      return `Open (deadline: ${program.enrollmentDeadline})`;
    }
    return 'Open';
  }
  if (program.enrollmentStatus === 'waitlist') {
    if (program.enrollmentOpens) {
      return `Waitlist (opens ${program.enrollmentOpens})`;
    }
    return 'Waitlist only';
  }
  return 'Closed';
}

export function formatSchoolYear(program: Program): string {
  if (program.schoolYearStart && program.schoolYearEnd) {
    return `${program.schoolYearStart} - ${program.schoolYearEnd}`;
  }
  return 'Year-round';
}

// Fixed distances from downtown Chicago (Willis Tower) for consistent demo
const FIXED_DISTANCES: Record<string, number> = {
  '1': 0.3,   // Willis Tower area
  '2': 3.8,   // Lincoln Park
  '3': 6.2,   // Lincoln Square
  '4': 4.1,   // Logan Square
  '5': 2.4,   // Gold Coast
  '6': 4.9,   // Lakeview
  '7': 3.5,   // Wicker Park
  '8': 1.1,   // River North
  '9': 3.9,   // Lincoln Park
  '10': 2.8,  // Pilsen
};

// Sample Chicago facilities with program-level data
export const sampleFacilities: Facility[] = [
  {
    id: '1',
    name: 'Bright Horizons at Willis Tower',
    facilityTypes: ['daycare', 'preschool'],
    address: '233 S Wacker Dr',
    city: 'Chicago',
    state: 'IL',
    zip: '60606',
    latitude: 41.8789,
    longitude: -87.6359,
    neighborhood: 'Loop',
    phone: '(312) 555-0101',
    website: 'https://brighthorizons.com',
    operatingHours: { open: '6:30 AM', close: '6:30 PM', days: 'Mon-Fri' },
    programs: [
      {
        id: 'p1-1',
        name: 'Infant Care',
        type: 'daycare',
        ageMinMonths: 6,
        ageMaxMonths: 12,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:00 AM',
        endTime: '5:00 PM',
        costAmount: 2800,
        costPeriod: 'monthly',
        costNotes: 'Full-time infant rate',
        enrollmentStatus: 'waitlist',
        enrollmentNotes: 'Typically 6-12 month waitlist',
        spotsTotal: 16,
        spotsAvailable: 0,
      },
      {
        id: 'p1-2',
        name: 'Toddler Program',
        type: 'daycare',
        ageMinMonths: 12,
        ageMaxMonths: 24,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:00 AM',
        endTime: '5:00 PM',
        costAmount: 2400,
        costPeriod: 'monthly',
        enrollmentStatus: 'waitlist',
        spotsTotal: 20,
        spotsAvailable: 0,
      },
      {
        id: 'p1-3',
        name: 'Preschool Full Day',
        type: 'preschool',
        ageMinMonths: 36,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 8,
        startTime: '8:00 AM',
        endTime: '4:00 PM',
        costAmount: 2100,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'March 15, 2025',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'June 13, 2026',
        spotsTotal: 24,
        spotsAvailable: 3,
      },
    ],
    licenseNumber: 'IL-2847561',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: true,
    languages: ['English', 'Spanish'],
    rating: 4.2,
    reviewCount: 47,
    distanceMiles: FIXED_DISTANCES['1'],
    lastUpdated: '2025-01-15',
  },
  {
    id: '2',
    name: 'Lincoln Park Montessori',
    facilityTypes: ['preschool', 'montessori', 'pre-k'],
    address: '2001 N Halsted St',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    latitude: 41.9178,
    longitude: -87.6484,
    neighborhood: 'Lincoln Park',
    phone: '(773) 555-0202',
    email: 'info@lpmontessori.edu',
    website: 'https://lpmontessori.edu',
    operatingHours: { open: '7:30 AM', close: '6:00 PM', days: 'Mon-Fri' },
    academicCalendar: {
      schoolYearStart: 'August 25, 2025',
      schoolYearEnd: 'June 5, 2026',
      enrollmentOpens: 'January 15, 2025',
      enrollmentDeadline: 'March 1, 2025',
      summerProgramAvailable: true,
      notes: 'Tours available by appointment',
    },
    programs: [
      {
        id: 'p2-1',
        name: 'Toddler Montessori',
        type: 'montessori',
        ageMinMonths: 18,
        ageMaxMonths: 36,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 4,
        startTime: '8:30 AM',
        endTime: '12:30 PM',
        costAmount: 1650,
        costPeriod: 'monthly',
        costNotes: 'Half-day program',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'March 1, 2025',
        schoolYearStart: 'August 25, 2025',
        schoolYearEnd: 'June 5, 2026',
        spotsTotal: 12,
        spotsAvailable: 2,
      },
      {
        id: 'p2-2',
        name: 'Primary Montessori Half Day',
        type: 'montessori',
        ageMinMonths: 36,
        ageMaxMonths: 72,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 3.5,
        startTime: '8:30 AM',
        endTime: '12:00 PM',
        costAmount: 1450,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'March 1, 2025',
        schoolYearStart: 'August 25, 2025',
        schoolYearEnd: 'June 5, 2026',
        spotsTotal: 24,
        spotsAvailable: 5,
      },
      {
        id: 'p2-3',
        name: 'Primary Montessori Full Day',
        type: 'montessori',
        ageMinMonths: 36,
        ageMaxMonths: 72,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 7,
        startTime: '8:30 AM',
        endTime: '3:30 PM',
        costAmount: 1950,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'March 1, 2025',
        schoolYearStart: 'August 25, 2025',
        schoolYearEnd: 'June 5, 2026',
        spotsTotal: 24,
        spotsAvailable: 3,
      },
    ],
    licenseNumber: 'IL-3156782',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: false,
    languages: ['English'],
    specialPrograms: ['Montessori certified', 'Outdoor classroom', 'Music enrichment'],
    rating: 4.8,
    reviewCount: 92,
    distanceMiles: FIXED_DISTANCES['2'],
    lastUpdated: '2025-01-20',
  },
  {
    id: '3',
    name: 'Little Scholars Academy',
    facilityTypes: ['daycare', 'preschool', 'pre-k'],
    address: '4521 N Western Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60625',
    latitude: 41.9634,
    longitude: -87.6879,
    neighborhood: 'Lincoln Square',
    phone: '(773) 555-0303',
    website: 'https://littlescholars.com',
    operatingHours: { open: '7:00 AM', close: '6:00 PM', days: 'Mon-Fri' },
    programs: [
      {
        id: 'p3-1',
        name: 'Toddler Care',
        type: 'daycare',
        ageMinMonths: 12,
        ageMaxMonths: 24,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 9,
        startTime: '8:00 AM',
        endTime: '5:00 PM',
        costAmount: 1650,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        spotsTotal: 16,
        spotsAvailable: 2,
      },
      {
        id: 'p3-2',
        name: 'Preschool 3-Day',
        type: 'preschool',
        ageMinMonths: 36,
        ageMaxMonths: 48,
        daysPerWeek: 3,
        daysOffered: ['Mon', 'Wed', 'Fri'],
        hoursPerDay: 4,
        startTime: '9:00 AM',
        endTime: '1:00 PM',
        costAmount: 850,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'May 29, 2026',
        spotsTotal: 16,
        spotsAvailable: 4,
      },
      {
        id: 'p3-3',
        name: 'Pre-K Full Day',
        type: 'pre-k',
        ageMinMonths: 48,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 7,
        startTime: '8:30 AM',
        endTime: '3:30 PM',
        costAmount: 1400,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'April 1, 2025',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'May 29, 2026',
        spotsTotal: 20,
        spotsAvailable: 6,
      },
    ],
    licenseNumber: 'IL-2934871',
    licenseStatus: 'active',
    hasTransportation: true,
    mealsProvided: true,
    languages: ['English', 'Polish'],
    specialPrograms: ['STEM curriculum', 'Music program'],
    rating: 4.5,
    reviewCount: 63,
    distanceMiles: FIXED_DISTANCES['3'],
    lastUpdated: '2025-01-18',
  },
  {
    id: '4',
    name: 'Sunshine Home Daycare',
    facilityTypes: ['home-daycare'],
    address: '2847 W Armitage Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60647',
    latitude: 41.9172,
    longitude: -87.6988,
    neighborhood: 'Logan Square',
    phone: '(773) 555-0404',
    operatingHours: { open: '7:30 AM', close: '5:30 PM', days: 'Mon-Fri' },
    programs: [
      {
        id: 'p4-1',
        name: 'Infant/Toddler Care',
        type: 'home-daycare',
        ageMinMonths: 3,
        ageMaxMonths: 36,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:30 AM',
        endTime: '5:30 PM',
        costAmount: 1200,
        costPeriod: 'monthly',
        costNotes: 'Sibling discount: 10% off second child',
        enrollmentStatus: 'open',
        enrollmentNotes: '2 spots currently available',
        spotsTotal: 8,
        spotsAvailable: 2,
      },
      {
        id: 'p4-2',
        name: 'Part-Time (3 days)',
        type: 'home-daycare',
        ageMinMonths: 3,
        ageMaxMonths: 36,
        daysPerWeek: 3,
        daysOffered: ['Mon', 'Wed', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:30 AM',
        endTime: '5:30 PM',
        costAmount: 800,
        costPeriod: 'monthly',
        enrollmentStatus: 'closed',
        enrollmentNotes: 'Currently full for part-time',
        spotsTotal: 2,
        spotsAvailable: 0,
      },
    ],
    licenseNumber: 'IL-HD-45872',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: true,
    languages: ['English', 'Spanish'],
    rating: 4.9,
    reviewCount: 12,
    distanceMiles: FIXED_DISTANCES['4'],
    lastUpdated: '2025-01-22',
  },
  {
    id: '5',
    name: 'CPS - Ogden Elementary',
    facilityTypes: ['pre-k', 'kindergarten', 'elementary'],
    address: '24 W Walton St',
    city: 'Chicago',
    state: 'IL',
    zip: '60610',
    latitude: 41.8998,
    longitude: -87.6291,
    neighborhood: 'Gold Coast',
    phone: '(773) 534-8920',
    website: 'https://ogden.cps.edu',
    operatingHours: { open: '8:00 AM', close: '3:30 PM', days: 'Mon-Fri' },
    academicCalendar: {
      schoolYearStart: 'August 26, 2025',
      schoolYearEnd: 'June 17, 2026',
      enrollmentOpens: 'March 1, 2025',
      enrollmentDeadline: 'April 15, 2025',
      summerProgramAvailable: false,
      notes: 'Magnet school - lottery-based admission',
    },
    programs: [
      {
        id: 'p5-1',
        name: 'Pre-K for All',
        type: 'pre-k',
        ageMinMonths: 48,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 2.5,
        startTime: '8:30 AM',
        endTime: '11:00 AM',
        costAmount: 0,
        costPeriod: 'yearly',
        costNotes: 'Free CPS program',
        enrollmentStatus: 'closed',
        enrollmentOpens: 'March 1, 2025',
        enrollmentDeadline: 'April 15, 2025',
        schoolYearStart: 'August 26, 2025',
        schoolYearEnd: 'June 17, 2026',
        enrollmentNotes: 'Lottery-based admission',
        spotsTotal: 40,
      },
      {
        id: 'p5-2',
        name: 'Kindergarten',
        type: 'kindergarten',
        ageMinMonths: 60,
        ageMaxMonths: 72,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 6.5,
        startTime: '8:30 AM',
        endTime: '3:00 PM',
        costAmount: 0,
        costPeriod: 'yearly',
        costNotes: 'Free public school',
        enrollmentStatus: 'closed',
        enrollmentOpens: 'March 1, 2025',
        enrollmentDeadline: 'April 15, 2025',
        schoolYearStart: 'August 26, 2025',
        schoolYearEnd: 'June 17, 2026',
        enrollmentNotes: 'Magnet school - requires application',
        spotsTotal: 75,
      },
    ],
    licenseStatus: 'active',
    hasTransportation: true,
    mealsProvided: true,
    languages: ['English'],
    specialPrograms: ['Gifted program', 'IB Primary Years', 'After-school enrichment'],
    rating: 4.3,
    reviewCount: 156,
    distanceMiles: FIXED_DISTANCES['5'],
    lastUpdated: '2025-01-10',
  },
  {
    id: '6',
    name: 'Kiddie Kare Learning Center',
    facilityTypes: ['daycare', 'preschool'],
    address: '3845 N Ashland Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60613',
    latitude: 41.9512,
    longitude: -87.6690,
    neighborhood: 'Lakeview',
    phone: '(773) 555-0606',
    website: 'https://kiddiekare.com',
    operatingHours: { open: '6:00 AM', close: '7:00 PM', days: 'Mon-Sat' },
    programs: [
      {
        id: 'p6-1',
        name: 'Infant Room',
        type: 'daycare',
        ageMinMonths: 6,
        ageMaxMonths: 15,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:00 AM',
        endTime: '5:00 PM',
        costAmount: 2100,
        costPeriod: 'monthly',
        enrollmentStatus: 'waitlist',
        spotsTotal: 12,
        spotsAvailable: 0,
      },
      {
        id: 'p6-2',
        name: 'Twos Program',
        type: 'daycare',
        ageMinMonths: 24,
        ageMaxMonths: 36,
        daysPerWeek: 3,
        daysOffered: ['Tue', 'Wed', 'Thu'],
        hoursPerDay: 5,
        startTime: '9:00 AM',
        endTime: '2:00 PM',
        costAmount: 975,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        spotsTotal: 16,
        spotsAvailable: 3,
      },
      {
        id: 'p6-3',
        name: 'Preschool Extended Day',
        type: 'preschool',
        ageMinMonths: 36,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:00 AM',
        endTime: '5:00 PM',
        costAmount: 1850,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        spotsTotal: 24,
        spotsAvailable: 5,
      },
    ],
    licenseNumber: 'IL-3047823',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: true,
    languages: ['English'],
    rating: 3.8,
    reviewCount: 34,
    distanceMiles: FIXED_DISTANCES['6'],
    lastUpdated: '2025-01-14',
  },
  {
    id: '7',
    name: 'Wicker Park Co-op Preschool',
    facilityTypes: ['preschool'],
    address: '1957 W Evergreen Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60622',
    latitude: 41.9065,
    longitude: -87.6774,
    neighborhood: 'Wicker Park',
    phone: '(773) 555-0707',
    email: 'admissions@wpcooppreschool.org',
    website: 'https://wpcooppreschool.org',
    operatingHours: { open: '8:30 AM', close: '12:30 PM', days: 'Mon-Thu' },
    academicCalendar: {
      schoolYearStart: 'September 8, 2025',
      schoolYearEnd: 'May 22, 2026',
      enrollmentOpens: 'February 1, 2025',
      enrollmentDeadline: 'February 28, 2025',
      summerProgramAvailable: false,
      notes: 'Lottery system for admission - parent participation required',
    },
    programs: [
      {
        id: 'p7-1',
        name: 'Young Twos',
        type: 'preschool',
        ageMinMonths: 24,
        ageMaxMonths: 36,
        daysPerWeek: 2,
        daysOffered: ['Tue', 'Thu'],
        hoursPerDay: 3,
        startTime: '9:00 AM',
        endTime: '12:00 PM',
        costAmount: 425,
        costPeriod: 'monthly',
        costNotes: 'Parent participation required (1x/month)',
        enrollmentStatus: 'closed',
        enrollmentOpens: 'February 1, 2025',
        enrollmentDeadline: 'February 28, 2025',
        schoolYearStart: 'September 8, 2025',
        schoolYearEnd: 'May 22, 2026',
        enrollmentNotes: 'Lottery system',
        spotsTotal: 12,
      },
      {
        id: 'p7-2',
        name: 'Threes/Fours',
        type: 'preschool',
        ageMinMonths: 36,
        ageMaxMonths: 60,
        daysPerWeek: 4,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu'],
        hoursPerDay: 3,
        startTime: '9:00 AM',
        endTime: '12:00 PM',
        costAmount: 850,
        costPeriod: 'monthly',
        costNotes: 'Parent participation required (2x/month)',
        enrollmentStatus: 'closed',
        enrollmentOpens: 'February 1, 2025',
        enrollmentDeadline: 'February 28, 2025',
        schoolYearStart: 'September 8, 2025',
        schoolYearEnd: 'May 22, 2026',
        enrollmentNotes: 'Lottery system',
        spotsTotal: 24,
      },
    ],
    licenseNumber: 'IL-2856934',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: false,
    languages: ['English'],
    specialPrograms: ['Play-based learning', 'Parent co-op', 'Nature curriculum'],
    rating: 4.7,
    reviewCount: 28,
    distanceMiles: FIXED_DISTANCES['7'],
    lastUpdated: '2025-01-19',
  },
  {
    id: '8',
    name: 'La Petite Academy - River North',
    facilityTypes: ['daycare', 'preschool', 'pre-k'],
    address: '401 N Wells St',
    city: 'Chicago',
    state: 'IL',
    zip: '60654',
    latitude: 41.8892,
    longitude: -87.6339,
    neighborhood: 'River North',
    phone: '(312) 555-0808',
    website: 'https://lapetite.com',
    operatingHours: { open: '6:30 AM', close: '6:30 PM', days: 'Mon-Fri' },
    programs: [
      {
        id: 'p8-1',
        name: 'Infant Care',
        type: 'daycare',
        ageMinMonths: 6,
        ageMaxMonths: 18,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 10,
        startTime: '7:00 AM',
        endTime: '5:00 PM',
        costAmount: 2650,
        costPeriod: 'monthly',
        enrollmentStatus: 'waitlist',
        spotsTotal: 18,
        spotsAvailable: 0,
      },
      {
        id: 'p8-2',
        name: 'Mandarin Immersion Preschool',
        type: 'preschool',
        ageMinMonths: 36,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 6,
        startTime: '9:00 AM',
        endTime: '3:00 PM',
        costAmount: 2200,
        costPeriod: 'monthly',
        costNotes: 'Mandarin immersion track',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'March 31, 2025',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'June 12, 2026',
        spotsTotal: 20,
        spotsAvailable: 4,
      },
      {
        id: 'p8-3',
        name: 'Pre-K Prep',
        type: 'pre-k',
        ageMinMonths: 48,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 6,
        startTime: '9:00 AM',
        endTime: '3:00 PM',
        costAmount: 1950,
        costPeriod: 'monthly',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'March 31, 2025',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'June 12, 2026',
        spotsTotal: 24,
        spotsAvailable: 7,
      },
    ],
    licenseNumber: 'IL-3182756',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: true,
    languages: ['English', 'Mandarin'],
    specialPrograms: ['Mandarin immersion', 'Early literacy', 'STEM exploration'],
    rating: 4.1,
    reviewCount: 89,
    distanceMiles: FIXED_DISTANCES['8'],
    lastUpdated: '2025-01-21',
  },
  {
    id: '9',
    name: 'St. Josaphat Parish School',
    facilityTypes: ['pre-k', 'kindergarten', 'elementary'],
    address: '2311 N Southport Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    latitude: 41.9235,
    longitude: -87.6637,
    neighborhood: 'Lincoln Park',
    phone: '(773) 555-0909',
    website: 'https://stjosaphatschool.org',
    operatingHours: { open: '7:30 AM', close: '6:00 PM', days: 'Mon-Fri' },
    academicCalendar: {
      schoolYearStart: 'August 25, 2025',
      schoolYearEnd: 'June 5, 2026',
      enrollmentOpens: 'January 6, 2025',
      enrollmentDeadline: 'January 31, 2025',
      summerProgramAvailable: true,
      notes: 'Parish members receive priority enrollment',
    },
    programs: [
      {
        id: 'p9-1',
        name: 'Pre-K 3s Half Day',
        type: 'pre-k',
        ageMinMonths: 36,
        ageMaxMonths: 48,
        daysPerWeek: 3,
        daysOffered: ['Mon', 'Wed', 'Fri'],
        hoursPerDay: 3,
        startTime: '8:30 AM',
        endTime: '11:30 AM',
        costAmount: 5800,
        costPeriod: 'yearly',
        costNotes: 'Parish member rate; non-member $7,200',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'January 31, 2025',
        schoolYearStart: 'August 25, 2025',
        schoolYearEnd: 'June 5, 2026',
        spotsTotal: 16,
        spotsAvailable: 4,
      },
      {
        id: 'p9-2',
        name: 'Pre-K 4s Full Day',
        type: 'pre-k',
        ageMinMonths: 48,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 7,
        startTime: '8:00 AM',
        endTime: '3:00 PM',
        costAmount: 8500,
        costPeriod: 'yearly',
        costNotes: 'Parish member rate; financial aid available',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'January 31, 2025',
        schoolYearStart: 'August 25, 2025',
        schoolYearEnd: 'June 5, 2026',
        spotsTotal: 24,
        spotsAvailable: 6,
      },
      {
        id: 'p9-3',
        name: 'Kindergarten',
        type: 'kindergarten',
        ageMinMonths: 60,
        ageMaxMonths: 72,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 7,
        startTime: '8:00 AM',
        endTime: '3:00 PM',
        costAmount: 8500,
        costPeriod: 'yearly',
        costNotes: 'Parish member rate; financial aid available',
        enrollmentStatus: 'open',
        enrollmentDeadline: 'January 31, 2025',
        schoolYearStart: 'August 25, 2025',
        schoolYearEnd: 'June 5, 2026',
        spotsTotal: 50,
        spotsAvailable: 12,
      },
    ],
    licenseStatus: 'active',
    hasTransportation: true,
    mealsProvided: true,
    languages: ['English'],
    specialPrograms: ['Catholic education', 'Extended care (3-6pm)', 'Summer camp'],
    rating: 4.4,
    reviewCount: 67,
    distanceMiles: FIXED_DISTANCES['9'],
    lastUpdated: '2025-01-16',
  },
  {
    id: '10',
    name: 'Pilsen Bilingual Preschool',
    facilityTypes: ['preschool', 'pre-k'],
    address: '1852 S Racine Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60608',
    latitude: 41.8565,
    longitude: -87.6567,
    neighborhood: 'Pilsen',
    phone: '(312) 555-1010',
    email: 'hola@pilsenbilingualpreschool.org',
    website: 'https://pilsenbilingualpreschool.org',
    operatingHours: { open: '7:30 AM', close: '5:30 PM', days: 'Mon-Fri' },
    academicCalendar: {
      schoolYearStart: 'September 2, 2025',
      schoolYearEnd: 'June 12, 2026',
      enrollmentOpens: 'Rolling admissions',
      summerProgramAvailable: true,
      notes: 'Spanish immersion - sliding scale tuition available',
    },
    programs: [
      {
        id: 'p10-1',
        name: 'Spanish Immersion - Twos',
        type: 'preschool',
        ageMinMonths: 24,
        ageMaxMonths: 36,
        daysPerWeek: 3,
        daysOffered: ['Mon', 'Wed', 'Fri'],
        hoursPerDay: 4,
        startTime: '9:00 AM',
        endTime: '1:00 PM',
        costAmount: 750,
        costPeriod: 'monthly',
        costNotes: 'Sliding scale available based on income',
        enrollmentStatus: 'open',
        enrollmentNotes: 'Rolling admissions',
        spotsTotal: 12,
        spotsAvailable: 3,
      },
      {
        id: 'p10-2',
        name: 'Spanish Immersion - Preschool',
        type: 'preschool',
        ageMinMonths: 36,
        ageMaxMonths: 48,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 6,
        startTime: '8:30 AM',
        endTime: '2:30 PM',
        costAmount: 1200,
        costPeriod: 'monthly',
        costNotes: 'Sliding scale available',
        enrollmentStatus: 'open',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'June 12, 2026',
        spotsTotal: 20,
        spotsAvailable: 5,
      },
      {
        id: 'p10-3',
        name: 'Spanish Immersion - Pre-K',
        type: 'pre-k',
        ageMinMonths: 48,
        ageMaxMonths: 60,
        daysPerWeek: 5,
        daysOffered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
        hoursPerDay: 7,
        startTime: '8:00 AM',
        endTime: '3:00 PM',
        costAmount: 1400,
        costPeriod: 'monthly',
        costNotes: 'Sliding scale available',
        enrollmentStatus: 'open',
        schoolYearStart: 'September 2, 2025',
        schoolYearEnd: 'June 12, 2026',
        spotsTotal: 20,
        spotsAvailable: 4,
      },
    ],
    licenseNumber: 'IL-2976543',
    licenseStatus: 'active',
    hasTransportation: false,
    mealsProvided: true,
    languages: ['Spanish', 'English'],
    specialPrograms: ['Spanish immersion', 'Cultural enrichment', 'Art program'],
    rating: 4.6,
    reviewCount: 41,
    distanceMiles: FIXED_DISTANCES['10'],
    lastUpdated: '2025-01-17',
  },
];
