import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

// Load environment variables from .env.local
config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing environment variables. Make sure .env.local exists with:');
  console.error('  NEXT_PUBLIC_SUPABASE_URL=your-url');
  console.error('  NEXT_PUBLIC_SUPABASE_ANON_KEY=your-key');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Sample Chicago facilities data
const facilities = [
  {
    name: 'Bright Horizons at Willis Tower',
    facility_types: ['daycare', 'preschool'],
    address: '233 S Wacker Dr',
    city: 'Chicago',
    state: 'IL',
    zip: '60606',
    latitude: 41.8789,
    longitude: -87.6359,
    neighborhood: 'Loop',
    phone: '(312) 555-0101',
    website: 'https://brighthorizons.com',
    operating_hours_open: '6:30 AM',
    operating_hours_close: '6:30 PM',
    operating_hours_days: 'Mon-Fri',
    license_number: 'IL-2847561',
    license_status: 'active',
    has_transportation: false,
    meals_provided: true,
    languages: ['English', 'Spanish'],
    special_programs: ['Corporate childcare'],
    rating: 4.2,
    review_count: 47,
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Lincoln Park Montessori',
    facility_types: ['preschool', 'montessori', 'pre-k'],
    address: '2001 N Halsted St',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    latitude: 41.9178,
    longitude: -87.6484,
    neighborhood: 'Lincoln Park',
    phone: '(773) 555-0202',
    email: 'info@lpmontessori.edu',
    website: 'https://lpmontessori.edu',
    operating_hours_open: '7:30 AM',
    operating_hours_close: '6:00 PM',
    operating_hours_days: 'Mon-Fri',
    license_number: 'IL-3156782',
    license_status: 'active',
    has_transportation: false,
    meals_provided: false,
    languages: ['English'],
    special_programs: ['Montessori certified', 'Outdoor classroom', 'Music enrichment'],
    rating: 4.8,
    review_count: 92,
    academic_calendar: {
      schoolYearStart: 'August 25, 2026',
      schoolYearEnd: 'June 5, 2027',
      enrollmentOpens: 'January 15, 2026',
      enrollmentDeadline: 'March 1, 2026',
      summerProgramAvailable: true,
      notes: 'Tours available by appointment',
    },
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Little Scholars Academy',
    facility_types: ['daycare', 'preschool', 'pre-k'],
    address: '4521 N Western Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60625',
    latitude: 41.9634,
    longitude: -87.6879,
    neighborhood: 'Lincoln Square',
    phone: '(773) 555-0303',
    website: 'https://littlescholars.com',
    operating_hours_open: '7:00 AM',
    operating_hours_close: '6:00 PM',
    operating_hours_days: 'Mon-Fri',
    license_number: 'IL-2934871',
    license_status: 'active',
    has_transportation: true,
    meals_provided: true,
    languages: ['English', 'Polish'],
    special_programs: ['STEM curriculum', 'Music program'],
    rating: 4.5,
    review_count: 63,
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Sunshine Home Daycare',
    facility_types: ['home-daycare'],
    address: '2847 W Armitage Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60647',
    latitude: 41.9172,
    longitude: -87.6988,
    neighborhood: 'Logan Square',
    phone: '(773) 555-0404',
    operating_hours_open: '7:30 AM',
    operating_hours_close: '5:30 PM',
    operating_hours_days: 'Mon-Fri',
    license_number: 'IL-HD-45872',
    license_status: 'active',
    has_transportation: false,
    meals_provided: true,
    languages: ['English', 'Spanish'],
    rating: 4.9,
    review_count: 12,
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Saint Andrew School',
    facility_types: ['pre-k', 'kindergarten', 'elementary'],
    address: '1710 W Addison St',
    city: 'Chicago',
    state: 'IL',
    zip: '60613',
    latitude: 41.9469,
    longitude: -87.6712,
    neighborhood: 'Lakeview',
    phone: '(773) 525-3770',
    website: 'https://standrew-school.org',
    operating_hours_open: '7:30 AM',
    operating_hours_close: '6:00 PM',
    operating_hours_days: 'Mon-Fri',
    license_status: 'active',
    has_transportation: false,
    meals_provided: true,
    languages: ['English'],
    special_programs: ['Catholic education', 'Extended care', 'Before/after school'],
    rating: 4.5,
    review_count: 38,
    academic_calendar: {
      schoolYearStart: 'August 26, 2026',
      schoolYearEnd: 'June 4, 2027',
      enrollmentOpens: 'January 2026',
      enrollmentDeadline: 'Contact school',
      notes: 'Parish families receive priority enrollment',
    },
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Kiddie Kare Learning Center',
    facility_types: ['daycare', 'preschool'],
    address: '3845 N Ashland Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60613',
    latitude: 41.9512,
    longitude: -87.6690,
    neighborhood: 'Lakeview',
    phone: '(773) 555-0606',
    website: 'https://kiddiekare.com',
    operating_hours_open: '6:00 AM',
    operating_hours_close: '7:00 PM',
    operating_hours_days: 'Mon-Sat',
    license_number: 'IL-3047823',
    license_status: 'active',
    has_transportation: false,
    meals_provided: true,
    languages: ['English'],
    rating: 3.8,
    review_count: 34,
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Wicker Park Co-op Preschool',
    facility_types: ['preschool'],
    address: '1957 W Evergreen Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60622',
    latitude: 41.9065,
    longitude: -87.6774,
    neighborhood: 'Wicker Park',
    phone: '(773) 555-0707',
    email: 'admissions@wpcooppreschool.org',
    website: 'https://wpcooppreschool.org',
    operating_hours_open: '9:00 AM',
    operating_hours_close: '12:00 PM',
    operating_hours_days: 'Mon-Thu',
    license_number: 'IL-2856934',
    license_status: 'active',
    has_transportation: false,
    meals_provided: false,
    languages: ['English'],
    special_programs: ['Play-based learning', 'Parent co-op'],
    rating: 4.7,
    review_count: 28,
    academic_calendar: {
      schoolYearStart: 'September 8, 2026',
      schoolYearEnd: 'May 28, 2027',
      enrollmentOpens: 'February 1, 2026',
      enrollmentDeadline: 'February 28, 2026',
      notes: 'Lottery system for admission',
    },
    last_updated: new Date().toISOString(),
  },
  {
    name: 'La Petite Academy - River North',
    facility_types: ['daycare', 'preschool', 'pre-k'],
    address: '401 N Wells St',
    city: 'Chicago',
    state: 'IL',
    zip: '60654',
    latitude: 41.8892,
    longitude: -87.6339,
    neighborhood: 'River North',
    phone: '(312) 555-0808',
    website: 'https://lapetite.com',
    operating_hours_open: '6:30 AM',
    operating_hours_close: '6:30 PM',
    operating_hours_days: 'Mon-Fri',
    license_number: 'IL-3182756',
    license_status: 'active',
    has_transportation: false,
    meals_provided: true,
    languages: ['English', 'Mandarin'],
    special_programs: ['Mandarin immersion', 'Early literacy', 'STEM exploration'],
    rating: 4.1,
    review_count: 89,
    last_updated: new Date().toISOString(),
  },
  {
    name: 'St. Josaphat Parish School',
    facility_types: ['pre-k', 'kindergarten', 'elementary'],
    address: '2311 N Southport Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    latitude: 41.9235,
    longitude: -87.6637,
    neighborhood: 'Lincoln Park',
    phone: '(773) 555-0909',
    website: 'https://stjosaphatschool.org',
    operating_hours_open: '7:30 AM',
    operating_hours_close: '6:00 PM',
    operating_hours_days: 'Mon-Fri',
    license_status: 'active',
    has_transportation: true,
    meals_provided: true,
    languages: ['English'],
    special_programs: ['Catholic education', 'Extended care (3-6pm)', 'Summer camp'],
    rating: 4.4,
    review_count: 67,
    academic_calendar: {
      schoolYearStart: 'August 25, 2026',
      schoolYearEnd: 'June 5, 2027',
      enrollmentOpens: 'January 6, 2026',
      enrollmentDeadline: 'January 31, 2026',
      summerProgramAvailable: true,
      notes: 'Parish members receive priority enrollment',
    },
    last_updated: new Date().toISOString(),
  },
  {
    name: 'Pilsen Bilingual Preschool',
    facility_types: ['preschool', 'pre-k'],
    address: '1852 S Racine Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60608',
    latitude: 41.8565,
    longitude: -87.6567,
    neighborhood: 'Pilsen',
    phone: '(312) 555-1010',
    email: 'hola@pilsenbilingualpreschool.org',
    website: 'https://pilsenbilingualpreschool.org',
    operating_hours_open: '7:30 AM',
    operating_hours_close: '5:30 PM',
    operating_hours_days: 'Mon-Fri',
    license_number: 'IL-2976543',
    license_status: 'active',
    has_transportation: false,
    meals_provided: true,
    languages: ['Spanish', 'English'],
    special_programs: ['Spanish immersion', 'Cultural enrichment', 'Art program'],
    rating: 4.6,
    review_count: 41,
    academic_calendar: {
      schoolYearStart: 'September 2, 2026',
      schoolYearEnd: 'June 12, 2027',
      enrollmentOpens: 'Rolling admissions',
      summerProgramAvailable: true,
      notes: 'Spanish immersion - sliding scale tuition available',
    },
    last_updated: new Date().toISOString(),
  },
];

// Programs for each facility
const programsByFacility: Record<string, any[]> = {
  'Bright Horizons at Willis Tower': [
    {
      name: 'Infant Care',
      program_type: 'daycare',
      age_min_months: 6,
      age_max_months: 12,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 10,
      start_time: '7:00 AM',
      end_time: '5:00 PM',
      cost_amount: 2800,
      cost_period: 'monthly',
      cost_notes: 'Full-time infant rate',
      enrollment_status: 'waitlist',
      enrollment_notes: 'Typically 6-12 month waitlist',
      spots_total: 16,
      spots_available: 0,
    },
    {
      name: 'Toddler Program',
      program_type: 'daycare',
      age_min_months: 12,
      age_max_months: 24,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 10,
      start_time: '7:00 AM',
      end_time: '5:00 PM',
      cost_amount: 2400,
      cost_period: 'monthly',
      enrollment_status: 'waitlist',
      spots_total: 20,
      spots_available: 0,
    },
    {
      name: 'Preschool Full Day',
      program_type: 'preschool',
      age_min_months: 36,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 8,
      start_time: '8:00 AM',
      end_time: '4:00 PM',
      cost_amount: 2100,
      cost_period: 'monthly',
      enrollment_status: 'open',
      enrollment_deadline: 'March 15, 2026',
      school_year_start: 'September 2, 2026',
      school_year_end: 'June 13, 2027',
      spots_total: 24,
      spots_available: 3,
    },
  ],
  'Lincoln Park Montessori': [
    {
      name: 'Toddler Montessori',
      program_type: 'montessori',
      age_min_months: 18,
      age_max_months: 36,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 4,
      start_time: '8:30 AM',
      end_time: '12:30 PM',
      cost_amount: 1650,
      cost_period: 'monthly',
      cost_notes: 'Half-day program',
      enrollment_status: 'open',
      enrollment_deadline: 'March 1, 2026',
      school_year_start: 'August 25, 2026',
      school_year_end: 'June 5, 2027',
      spots_total: 12,
      spots_available: 2,
    },
    {
      name: 'Primary Montessori Half Day',
      program_type: 'montessori',
      age_min_months: 36,
      age_max_months: 72,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 3.5,
      start_time: '8:30 AM',
      end_time: '12:00 PM',
      cost_amount: 1450,
      cost_period: 'monthly',
      enrollment_status: 'open',
      enrollment_deadline: 'March 1, 2026',
      school_year_start: 'August 25, 2026',
      school_year_end: 'June 5, 2027',
      spots_total: 24,
      spots_available: 5,
    },
    {
      name: 'Primary Montessori Full Day',
      program_type: 'montessori',
      age_min_months: 36,
      age_max_months: 72,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:30 AM',
      end_time: '3:30 PM',
      cost_amount: 1950,
      cost_period: 'monthly',
      enrollment_status: 'open',
      enrollment_deadline: 'March 1, 2026',
      school_year_start: 'August 25, 2026',
      school_year_end: 'June 5, 2027',
      spots_total: 24,
      spots_available: 3,
    },
  ],
  'Little Scholars Academy': [
    {
      name: 'Toddler Room',
      program_type: 'daycare',
      age_min_months: 12,
      age_max_months: 24,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 9,
      start_time: '8:00 AM',
      end_time: '5:00 PM',
      cost_amount: 1850,
      cost_period: 'monthly',
      enrollment_status: 'open',
      spots_total: 16,
      spots_available: 2,
    },
    {
      name: 'Preschool Program',
      program_type: 'preschool',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 6,
      start_time: '9:00 AM',
      end_time: '3:00 PM',
      cost_amount: 1650,
      cost_period: 'monthly',
      enrollment_status: 'open',
      spots_total: 20,
      spots_available: 4,
    },
    {
      name: 'Pre-K STEM',
      program_type: 'pre-k',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 6,
      start_time: '9:00 AM',
      end_time: '3:00 PM',
      cost_amount: 1750,
      cost_period: 'monthly',
      cost_notes: 'STEM-focused curriculum',
      enrollment_status: 'open',
      school_year_start: 'September 2, 2026',
      school_year_end: 'June 12, 2027',
      spots_total: 20,
      spots_available: 6,
    },
  ],
  'Sunshine Home Daycare': [
    {
      name: 'Infant/Toddler Care',
      program_type: 'home-daycare',
      age_min_months: 3,
      age_max_months: 36,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 10,
      start_time: '7:30 AM',
      end_time: '5:30 PM',
      cost_amount: 1200,
      cost_period: 'monthly',
      cost_notes: 'Sibling discount available',
      enrollment_status: 'open',
      enrollment_notes: '2 spots available',
      spots_total: 8,
      spots_available: 2,
    },
  ],
  'Saint Andrew School': [
    {
      name: 'Pre-K 3s Full Day',
      program_type: 'pre-k',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:00 AM',
      end_time: '3:00 PM',
      cost_amount: null,
      cost_period: 'yearly',
      cost_notes: 'Contact school for tuition; must be 3 by September 1',
      enrollment_status: 'open',
      enrollment_notes: 'Full day option for 3-year-olds',
      school_year_start: 'August 26, 2026',
      school_year_end: 'June 4, 2027',
    },
    {
      name: 'Pre-K 3s Half Day',
      program_type: 'pre-k',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 3,
      start_time: '8:00 AM',
      end_time: '11:00 AM',
      cost_amount: null,
      cost_period: 'yearly',
      cost_notes: 'Contact school for tuition; must be 3 by September 1',
      enrollment_status: 'open',
      enrollment_notes: 'Half day option for 3-year-olds',
      school_year_start: 'August 26, 2026',
      school_year_end: 'June 4, 2027',
    },
    {
      name: 'Pre-K 3s M-W-F Only',
      program_type: 'pre-k',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 3,
      days_offered: ['Mon', 'Wed', 'Fri'],
      hours_per_day: 3,
      start_time: '8:00 AM',
      end_time: '11:00 AM',
      cost_amount: null,
      cost_period: 'yearly',
      cost_notes: 'Contact school for tuition; must be 3 by September 1',
      enrollment_status: 'open',
      enrollment_notes: 'Part-week option for 3-year-olds only',
      school_year_start: 'August 26, 2026',
      school_year_end: 'June 4, 2027',
    },
    {
      name: 'Pre-K 4s Full Day',
      program_type: 'pre-k',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:00 AM',
      end_time: '3:00 PM',
      cost_amount: null,
      cost_period: 'yearly',
      cost_notes: 'Contact school for tuition; must be 4 by September 1',
      enrollment_status: 'open',
      school_year_start: 'August 26, 2026',
      school_year_end: 'June 4, 2027',
    },
    {
      name: 'Pre-K 4s Half Day',
      program_type: 'pre-k',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 3,
      start_time: '8:00 AM',
      end_time: '11:00 AM',
      cost_amount: null,
      cost_period: 'yearly',
      cost_notes: 'Contact school for tuition; must be 4 by September 1',
      enrollment_status: 'open',
      school_year_start: 'August 26, 2026',
      school_year_end: 'June 4, 2027',
    },
    {
      name: 'Kindergarten',
      program_type: 'kindergarten',
      age_min_months: 60,
      age_max_months: 72,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:00 AM',
      end_time: '3:00 PM',
      cost_amount: null,
      cost_period: 'yearly',
      cost_notes: 'Contact school for tuition; must be 5 by September 1',
      enrollment_status: 'open',
      school_year_start: 'August 26, 2026',
      school_year_end: 'June 4, 2027',
    },
  ],
  'Kiddie Kare Learning Center': [
    {
      name: 'Infant Care',
      program_type: 'daycare',
      age_min_months: 6,
      age_max_months: 12,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 10,
      start_time: '7:00 AM',
      end_time: '5:00 PM',
      cost_amount: 2100,
      cost_period: 'monthly',
      enrollment_status: 'waitlist',
      spots_total: 12,
      spots_available: 0,
    },
    {
      name: 'Preschool',
      program_type: 'preschool',
      age_min_months: 36,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 8,
      start_time: '8:00 AM',
      end_time: '4:00 PM',
      cost_amount: 1800,
      cost_period: 'monthly',
      enrollment_status: 'open',
      spots_total: 24,
      spots_available: 5,
    },
  ],
  'Wicker Park Co-op Preschool': [
    {
      name: '2s Program',
      program_type: 'preschool',
      age_min_months: 24,
      age_max_months: 36,
      days_per_week: 2,
      days_offered: ['Tue', 'Thu'],
      hours_per_day: 3,
      start_time: '9:00 AM',
      end_time: '12:00 PM',
      cost_amount: 450,
      cost_period: 'monthly',
      cost_notes: 'Parent participation required (1 day/month)',
      enrollment_status: 'closed',
      enrollment_opens: 'February 1, 2026',
      enrollment_deadline: 'February 28, 2026',
      enrollment_notes: 'Lottery system for admission',
      school_year_start: 'September 8, 2026',
      school_year_end: 'May 28, 2027',
      spots_total: 12,
      spots_available: 0,
    },
    {
      name: '3s Program',
      program_type: 'preschool',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 3,
      days_offered: ['Mon', 'Wed', 'Fri'],
      hours_per_day: 3,
      start_time: '9:00 AM',
      end_time: '12:00 PM',
      cost_amount: 650,
      cost_period: 'monthly',
      cost_notes: 'Parent participation required (1 day/month)',
      enrollment_status: 'closed',
      enrollment_opens: 'February 1, 2026',
      enrollment_deadline: 'February 28, 2026',
      enrollment_notes: 'Lottery system for admission',
      school_year_start: 'September 8, 2026',
      school_year_end: 'May 28, 2027',
      spots_total: 16,
      spots_available: 0,
    },
    {
      name: '4s Program',
      program_type: 'preschool',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 4,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu'],
      hours_per_day: 3,
      start_time: '9:00 AM',
      end_time: '12:00 PM',
      cost_amount: 850,
      cost_period: 'monthly',
      cost_notes: 'Parent participation required (1 day/month)',
      enrollment_status: 'closed',
      enrollment_opens: 'February 1, 2026',
      enrollment_deadline: 'February 28, 2026',
      enrollment_notes: 'Lottery system for admission',
      school_year_start: 'September 8, 2026',
      school_year_end: 'May 28, 2027',
      spots_total: 16,
      spots_available: 0,
    },
  ],
  'La Petite Academy - River North': [
    {
      name: 'Infant Care',
      program_type: 'daycare',
      age_min_months: 6,
      age_max_months: 18,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 10,
      start_time: '7:00 AM',
      end_time: '5:00 PM',
      cost_amount: 2650,
      cost_period: 'monthly',
      enrollment_status: 'waitlist',
      spots_total: 18,
      spots_available: 0,
    },
    {
      name: 'Mandarin Immersion Preschool',
      program_type: 'preschool',
      age_min_months: 36,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 6,
      start_time: '9:00 AM',
      end_time: '3:00 PM',
      cost_amount: 2200,
      cost_period: 'monthly',
      cost_notes: 'Mandarin immersion track',
      enrollment_status: 'open',
      enrollment_deadline: 'March 31, 2026',
      school_year_start: 'September 2, 2026',
      school_year_end: 'June 12, 2027',
      spots_total: 20,
      spots_available: 4,
    },
    {
      name: 'Pre-K Prep',
      program_type: 'pre-k',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 6,
      start_time: '9:00 AM',
      end_time: '3:00 PM',
      cost_amount: 1950,
      cost_period: 'monthly',
      enrollment_status: 'open',
      enrollment_deadline: 'March 31, 2026',
      school_year_start: 'September 2, 2026',
      school_year_end: 'June 12, 2027',
      spots_total: 24,
      spots_available: 7,
    },
  ],
  'St. Josaphat Parish School': [
    {
      name: 'Pre-K 3s Half Day',
      program_type: 'pre-k',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 3,
      days_offered: ['Mon', 'Wed', 'Fri'],
      hours_per_day: 3,
      start_time: '8:30 AM',
      end_time: '11:30 AM',
      cost_amount: 5800,
      cost_period: 'yearly',
      cost_notes: 'Parish member rate; non-member $7,200',
      enrollment_status: 'open',
      enrollment_deadline: 'January 31, 2026',
      school_year_start: 'August 25, 2026',
      school_year_end: 'June 5, 2027',
      spots_total: 16,
      spots_available: 4,
    },
    {
      name: 'Pre-K 4s Full Day',
      program_type: 'pre-k',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:00 AM',
      end_time: '3:00 PM',
      cost_amount: 8500,
      cost_period: 'yearly',
      cost_notes: 'Parish member rate; financial aid available',
      enrollment_status: 'open',
      enrollment_deadline: 'January 31, 2026',
      school_year_start: 'August 25, 2026',
      school_year_end: 'June 5, 2027',
      spots_total: 24,
      spots_available: 6,
    },
    {
      name: 'Kindergarten',
      program_type: 'kindergarten',
      age_min_months: 60,
      age_max_months: 72,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:00 AM',
      end_time: '3:00 PM',
      cost_amount: 8500,
      cost_period: 'yearly',
      cost_notes: 'Parish member rate; financial aid available',
      enrollment_status: 'open',
      enrollment_deadline: 'January 31, 2026',
      school_year_start: 'August 25, 2026',
      school_year_end: 'June 5, 2027',
      spots_total: 50,
      spots_available: 12,
    },
  ],
  'Pilsen Bilingual Preschool': [
    {
      name: 'Spanish Immersion - Twos',
      program_type: 'preschool',
      age_min_months: 24,
      age_max_months: 36,
      days_per_week: 3,
      days_offered: ['Mon', 'Wed', 'Fri'],
      hours_per_day: 4,
      start_time: '9:00 AM',
      end_time: '1:00 PM',
      cost_amount: 750,
      cost_period: 'monthly',
      cost_notes: 'Sliding scale available based on income',
      enrollment_status: 'open',
      enrollment_notes: 'Rolling admissions',
      spots_total: 12,
      spots_available: 3,
    },
    {
      name: 'Spanish Immersion - Preschool',
      program_type: 'preschool',
      age_min_months: 36,
      age_max_months: 48,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 6,
      start_time: '8:30 AM',
      end_time: '2:30 PM',
      cost_amount: 1200,
      cost_period: 'monthly',
      cost_notes: 'Sliding scale available',
      enrollment_status: 'open',
      school_year_start: 'September 2, 2026',
      school_year_end: 'June 12, 2027',
      spots_total: 20,
      spots_available: 5,
    },
    {
      name: 'Spanish Immersion - Pre-K',
      program_type: 'pre-k',
      age_min_months: 48,
      age_max_months: 60,
      days_per_week: 5,
      days_offered: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
      hours_per_day: 7,
      start_time: '8:00 AM',
      end_time: '3:00 PM',
      cost_amount: 1400,
      cost_period: 'monthly',
      cost_notes: 'Sliding scale available',
      enrollment_status: 'open',
      school_year_start: 'September 2, 2026',
      school_year_end: 'June 12, 2027',
      spots_total: 20,
      spots_available: 4,
    },
  ],
};

async function seed() {
  console.log('🌱 Starting seed...\n');

  // Clear existing data - delete all rows
  console.log('Clearing existing data...');
  const { error: progDelError } = await supabase.from('programs').delete().gte('created_at', '1970-01-01');
  if (progDelError) console.error('Error clearing programs:', progDelError.message);
  
  const { error: facDelError } = await supabase.from('facilities').delete().gte('created_at', '1970-01-01');
  if (facDelError) console.error('Error clearing facilities:', facDelError.message);
  
  console.log('Cleared existing data.\n');

  // Insert facilities
  console.log('Inserting facilities...');
  for (const facility of facilities) {
    const { data, error } = await supabase
      .from('facilities')
      .insert(facility)
      .select()
      .single();

    if (error) {
      console.error(`Error inserting ${facility.name}:`, error.message);
      continue;
    }

    console.log(`  ✓ ${facility.name}`);

    // Insert programs for this facility
    const programs = programsByFacility[facility.name];
    if (programs && data) {
      for (const program of programs) {
        const { error: progError } = await supabase
          .from('programs')
          .insert({ ...program, facility_id: data.id });

        if (progError) {
          console.error(`    Error inserting program ${program.name}:`, progError.message);
        } else {
          console.log(`    + ${program.name}`);
        }
      }
    }
  }

  console.log('\n✅ Seed complete!');
}

seed().catch(console.error);
